export enum CategoryEnum {
  Consultorio = "Consultorio",
  CentroDeEstetica = "Centro de estética",
  CejasYPestanas = "Cejas y Pestañas",
  Spa = "Spa",
  Maquillaje = "Maquillaje",
  Unas = "Uñas",
  Masajes = "Masajes",
  Depilacion = "Depilación",
  Tatuajes = "Tatuajes",
  Peluqueria = "Peluquería",
  Barberia = "Barbería",
  PeluqueriaMascotas = "Peluquería Mascotas",
  Asesorias = "",
  ClasesParticulares = "Clases particulares",
  Fotografia = "Fotografía",
  Otro = "Otro",
}

export const CATEGORY_VALUES = [
  CategoryEnum.Consultorio,
  CategoryEnum.CentroDeEstetica,
  CategoryEnum.CejasYPestanas,
  CategoryEnum.Spa,
  CategoryEnum.Maquillaje,
  CategoryEnum.Unas,
  CategoryEnum.Masajes,
  CategoryEnum.Depilacion,
  CategoryEnum.Tatuajes,
  CategoryEnum.Peluqueria,
  CategoryEnum.Barberia,
  CategoryEnum.PeluqueriaMascotas,
  CategoryEnum.Asesorias,
  CategoryEnum.ClasesParticulares,
  CategoryEnum.Fotografia,
  CategoryEnum.Otro,
] as const;
export type Category = (typeof CATEGORY_VALUES)[number];
